"""add_unique_constraint_on_provider_by_router_id

Revision ID: 1db1572f2605
Revises: 2d2550e0771d
Create Date: 2025-12-16 15:35:24.144867

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1db1572f2605'
down_revision: Union[str, None] = '2d2550e0771d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('unique_provider_url_model_name'), 'provider', type_='unique')
    op.create_unique_constraint('unique_provider_router_id_url_model_name', 'provider', ['router_id', 'url', 'model_name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('unique_provider_router_id_url_model_name', 'provider', type_='unique')
    op.create_unique_constraint(op.f('unique_provider_url_model_name'), 'provider', ['url', 'model_name'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
