"""force non null email

Revision ID: 17be379f45ac
Revises: 479aeeae940b
Create Date: 2025-09-07 12:46:08.812624

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "17be379f45ac"
down_revision: Union[str, None] = "479aeeae940b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("iss", sa.String(), nullable=True))
    # Backfill: copy values from name to email where email is NULL
    op.execute('UPDATE "user" SET email = name WHERE email IS NULL AND name IS NOT NULL;')
    op.alter_column("user", "email", existing_type=sa.VARCHAR(length=255), nullable=False)
    op.alter_column("user", "name", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index("ix_user_name", table_name="user")
    op.drop_constraint("uq_user_sub", "user", type_="unique")
    op.drop_index("ix_user_email", table_name="user")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_unique_constraint("unique_user_email_sub_iss", "user", ["sub", "iss"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("unique_user_email_sub_iss", "user", type_="unique")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_index("ix_user_email", "user", ["email"], unique=False)
    op.create_unique_constraint("uq_user_sub", "user", ["sub"])
    op.create_index("ix_user_name", "user", ["name"], unique=True)
    op.alter_column("user", "name", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("user", "email", existing_type=sa.VARCHAR(length=255), nullable=True)
    op.drop_column("user", "iss")
    # ### end Alembic commands ###
