"""rename usage columns

Revision ID: 843230e94aec
Revises: 0ae7dc72ec5c
Create Date: 2025-11-19 17:11:49.797717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
from sqlalchemy import func

# revision identifiers, used by Alembic.
revision: str = '843230e94aec'
down_revision: Union[str, None] = '0ae7dc72ec5c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('created', sa.DateTime(), nullable=False, server_default=func.now()))
    op.add_column('usage', sa.Column('latency', sa.Integer(), nullable=True))
    op.add_column('usage', sa.Column('ttft', sa.Integer(), nullable=True))
    
    # Copy datetime -> created
    op.execute("""
        UPDATE usage
        SET created = datetime
        WHERE datetime IS NOT NULL
    """)

    # Copy model -> provider_model_name
    op.execute("""
        UPDATE usage
        SET latency = duration
        WHERE duration IS NOT NULL
    """)

    # Copy ttft -> time_to_first_token
    op.execute("""
        UPDATE usage
        SET ttft = time_to_first_token
        WHERE time_to_first_token IS NOT NULL
    """)

    
    op.drop_column('usage', 'time_to_first_token')
    op.drop_column('usage', 'datetime')
    op.drop_column('usage', 'duration')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('usage', sa.Column('duration', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('usage', sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('usage', sa.Column('time_to_first_token', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('usage', 'ttft')
    op.drop_column('usage', 'latency')
    op.drop_column('usage', 'created')
    # ### end Alembic commands ###
