"""add_default_value_carbon_params

Revision ID: d2e9e967501b
Revises: 1db1572f2605
Create Date: 2025-12-16 17:37:52.732163

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd2e9e967501b'
down_revision: Union[str, None] = '1db1572f2605'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE provider SET model_carbon_footprint_total_params = 0 WHERE model_carbon_footprint_total_params IS NULL")
    op.execute("UPDATE provider SET model_carbon_footprint_active_params = 0 WHERE model_carbon_footprint_active_params IS NULL")

    op.alter_column('provider', 'model_carbon_footprint_total_params',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('provider', 'model_carbon_footprint_active_params',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provider', 'model_carbon_footprint_active_params',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('provider', 'model_carbon_footprint_total_params',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
