"""add_provider_router_list_relationship

Revision ID: 551b2920b23c
Revises: d2e9e967501b
Create Date: 2025-12-17 09:47:44.993566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '551b2920b23c'
down_revision: Union[str, None] = 'd2e9e967501b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE provider SET timeout = 300 WHERE timeout IS NULL")

    op.alter_column('provider', 'timeout',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('provider', 'timeout',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
